spring:
  application:
    name: delivery-service

  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/delivery
    username: delivery
    password: delivery
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG

secret: L7j/9tPqi+CRvydIyWF71HYD4L9ymUhAskSmrfeyrEU=
expiration: 604800000